baseURL = "https://www.deobald.ca"
languageCode = "en-us"
title = "Steven Deobald"
theme = "hyde-hyde"
publishDir = "../docs"

# generates the sidebar
sectionPagesMenu = "main"

[params]
  # hides the automatic prev/next links at the bottom of essays
  postNavigation = false
  essayNavigation = false

[params.social]
  gravatar = "steven@deobald.ca"
  mastodon = "@deobald"
  bluesky = "deobald.bsky.social"
  github = "deobald"
  email = "steven@deobald.ca"

[[menu.main]]
  name = "RSS Feed"
  url = "/index.xml"

[markup]
  [markup.asciidocExt]
    backend = 'html5s'
    extensions = ["asciidoctor-html5s"]

[security]
  enableInlineShortcodes = false

  [security.exec]
    allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv = ['(?i)^((HTTPS?|NO)_PROXY|PATH(EXT)?|APPDATA|TE?MP|TERM|RUBYLIB)$']

  [security.funcs]
    getenv = ['^HUGO_']

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']
