baseURL = "https://www.deobald.ca"
languageCode = "en-us"
title = "Steven Deobald"
theme = "hyde-hyde"
publishDir = "../docs"

# generates the sidebar
sectionPagesMenu = "main"

[params.social]
  twitter = "deobald"
  keybase = "deobald"
  github = "deobald"
