baseURL = "https://www.deobald.ca"
languageCode = "en-us"
title = "Steven Deobald"
theme = "hyde-hyde"
publishDir = "../docs"
googleAnalytics = "UA-155302034-1"

# generates the sidebar
sectionPagesMenu = "main"

[params]
  # hides the automatic prev/next links at the bottom of essays
  postNavigation = false
  essayNavigation = false

[params.social]
  gravatar = "steven@deobald.ca"
  twitter = "deobald"
  github = "deobald"
  keybase = "deobald"
  email = "steven@deobald.ca"

[[menu.main]]
  name = "RSS Feed"
  url = "/index.xml"

[markup]
  [markup.asciidocExt]
    backend = 'html5s'
    extensions = ["asciidoctor-html5s"]
